export const ADD_ERROR = 'ADD_ERROR';
export const REMOVE_ERROR = 'REMOVE_ERROR';
export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const LOAD_MESSAGES = 'LOAD_MESSAGES';
export const REMOVE_MESSAGE = 'REMOVE_MESSAGE';
export const LOAD_USER_MESSAGES = 'LOAD_USER_MESSAGES'; 
export const LOAD_USER = 'LOAD_USER';